name: Build on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        brew update
        brew install gcc make cmake pkg-config
        
    - name: Set up compiler
      run: |
        GCC_VERSION=$(brew list --versions gcc | grep -o '[0-9]\+' | head -1)
        echo "CPPC=g++-$GCC_VERSION" >> $GITHUB_ENV
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(sysctl -n hw.ncpu)
        cd ..        
